### ISSUE TITLE
The plugin won't work with sketchpacks plugin

### ISSUE THREAD

**Issue by YaronTm** [preciousforever/sketch-aspect-ratio#2]
When trying to install it with sketchpacks plugin it won't show in the plugin menu..

**Comment by studiostoll** [comment]
Known issue, we'll fix it asap.

**Comment by Swiftnesses** [comment]
Is this going to be fixed?

**Comment by studiostoll** [comment]
@Swiftnesses @YaronTm it should be fixed. can you confirm or re-open?
